name: Deploy to Vercel

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Vercel CLI
      run: npm i -g vercel

    - name: Deploy to Vercel
      run: vercel --token ${{ secrets.PIPELINE }} --yes
      env:
        VERCEL_ORG_ID: ${{ secrets.FryolyWlDASOvCqQSGp7QMMx }}
        VERCEL_PROJECT_ID: ${{ secrets.prj_id8kfDaAmD6lp219jgyU43RwixuD }}